### ISSUE TITLE
What are the supported php and mysql versions?

### ISSUE THREAD

**Issue by pubterra** [ajaxray/static-pdo#2]
Hi, 
I upgraded my DB file after years of using an older version and my app broke. Would you share what versions the current DB file supports?

Thank you!

**Comment by ajaxray** [comment]
Hello @pubterra ,

Thaks a lot for asking.

As mentioned in composer.json, it should work for `"php": ">=5.3"`
But I didn't test it with PHP 7.x (will do soon as you've reported an error).

Can you please mention your PHP version and the error you've caught?

**Comment by pubterra** [comment]
Thanks for getting back to me @ajaxray. I'm using PHP 7.0.33 and mysql 5.7.29. The error I'm getting is "Fatal error: Uncaught Error: Class 'Db' not found in /var/www/html/_tApi/v3/test.php:8 Stack trace: #0 {main} thrown in /var/www/html/_tApi/v3/test.php on line 8. In this case I'm using your example file because I wasn't certain it was my code. The error is the same in every case. The line being referenced is Db::setConnectionInfo(...).

I tried a few different variations to try to connect to my database. The code that works is: 
              $db = new PDO("mysql:host=localhost;dbname=database_name", 'user_name','password');
I wonder if it's just the order of arguments in the setConnectionInfo method...

**Comment by pubterra** [comment]
I resolved the issue.
